import Head from 'next/head'
import Nav from '@/components/nav'
import { useState, useEffect } from 'react'
import type { Product } from '@/types/types'
import { ProductCard } from '@/components/products'

export default function Home(): JSX.Element {
  const [products, setProducts] = useState<Product[] | []>([])
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    async function fetchproducts() {
      const response = await fetch('/api/products')
      const products: Product[] = await response.json()
      setProducts(products)
      setLoading(false)
    }
    fetchproducts()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        {loading ? (
          <p>Loading...</p>
        ) : (
          products.map((product) => {
            return <ProductCard key={product.uuId} productData={product} />
            })
        )}
      </main>
    </>
  )
}
