import Head from 'next/head'
import Nav from '@/components/nav'
import { useEffect } from 'react'
import type { Product } from '@/types/types'

export default function Home(): JSX.Element {
  useEffect(() => {
    async function fetchproducts() {
      const response = await fetch('/api/products')
      const products: Product = await response.json()
      console.log(products)
    }
    fetchproducts()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
      </main>
    </>
  )
}
