import Head from 'next/head'
import {ProductsInfinitScroll} from '@/components/products'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductsInfinitScroll />
      </main>
    </>
  )
}
